title = "Focux app gitleaks"

[allowlist]
paths = [
  '''^.*\.example$''',
  '''^.*SECURITY\.md$''',
  '''^.*README\.md$''',
  '''^.*\.gitleaks\.toml$'''
]
regexes = [
  '''AIzaSyDN''',
  '''API_KEY_PREFIX'''
]
