/// Fixture espelhando o shape do BFF (hubs + abas + legacyIds).
Map<String, dynamic> catalogoFixtureJson() => {
  'version': 3,
  'plano': 'PRO',
  'atalhosHome': [
    {
      'id': 'leads',
      'titulo': 'Leads',
      'rotaApp': '/leads',
      'featureGate': 'LEADS',
      'unlocked': true,
      'papel': 'essencial',
      'legacyIds': ['leads'],
      'abas': [],
      'destaqueHome': true,
    },
    {
      'id': 'saude-base',
      'titulo': 'Saúde da base',
      'rotaApp': '/retencao',
      'unlocked': true,
      'papel': 'essencial',
      'legacyIds': ['recuperacao', 'retencao'],
      'abas': [],
      'destaqueHome': true,
    },
    {
      'id': 'configuracao-inicial',
      'titulo': 'Configuração inicial',
      'rotaApp': '/onboarding/wizard',
      'unlocked': true,
      'papel': 'conta',
      'legacyIds': ['onboarding'],
      'abas': [],
    },
  ],
  'hubs': [
    {
      'id': 'operacao',
      'titulo': 'Operação',
      'papel': 'essencial',
      'itens': [
        {
          'id': 'exercicios',
          'titulo': 'Exercícios',
          'rotaApp': '/exercicios',
          'unlocked': true,
          'papel': 'essencial',
          'legacyIds': ['exercicios'],
          'abas': [],
        },
        {
          'id': 'feed',
          'titulo': 'Feed',
          'rotaApp': '/feed',
          'unlocked': true,
          'papel': 'util',
          'legacyIds': ['feed'],
          'abas': [],
        },
      ],
    },
    {
      'id': 'captacao',
      'titulo': 'Captação',
      'subtitulo': 'Leads públicos e landing',
      'papel': 'essencial',
      'itens': [
        {
          'id': 'hub-captacao',
          'titulo': 'Captação',
          'unlocked': true,
          'papel': 'essencial',
          'legacyIds': ['lead-publico', 'landing', 'Lead Público'],
          'abas': [
            {
              'id': 'leads-publicos',
              'titulo': 'Lead Público',
              'rotaApp': '/leads-publicos',
              'featureGate': 'FINANCEIRO',
              'unlocked': true,
              'legacyIds': ['lead-publico', 'Lead Público'],
              'abas': [],
            },
            {
              'id': 'landing',
              'titulo': 'Landing',
              'rotaApp': '/perfil/landing-editor',
              'featureGate': 'LANDING_COMPLETA',
              'unlocked': false,
              'upgradePlano': 'ENTERPRISE',
              'legacyIds': ['landing'],
              'abas': [],
            },
          ],
        },
      ],
    },
    {
      'id': 'vendas',
      'titulo': 'Vendas',
      'papel': 'essencial',
      'itens': [
        {
          'id': 'hub-vendas',
          'titulo': 'Vendas',
          'unlocked': true,
          'papel': 'essencial',
          'legacyIds': ['pacotes', 'loja'],
          'abas': [
            {
              'id': 'pacotes',
              'titulo': 'Pacotes',
              'rotaApp': '/pacotes',
              'featureGate': 'LOJA_DIGITAL',
              'unlocked': true,
              'legacyIds': ['pacotes'],
              'abas': [],
            },
            {
              'id': 'loja',
              'titulo': 'Loja',
              'rotaApp': '/loja',
              'featureGate': 'LOJA_DIGITAL',
              'unlocked': false,
              'upgradePlano': 'ENTERPRISE',
              'legacyIds': ['loja'],
              'abas': [],
            },
          ],
        },
      ],
    },
    {
      'id': 'financeiro',
      'titulo': 'Financeiro',
      'papel': 'essencial',
      'itens': [
        {
          'id': 'hub-financeiro',
          'titulo': 'Financeiro',
          'unlocked': true,
          'papel': 'essencial',
          'legacyIds': [
            'receita-recorrente',
            'recorrencia',
            'cobranca-auto',
            'Receita recorrente',
          ],
          'abas': [
            {
              'id': 'receita-recorrente',
              'titulo': 'Receita recorrente',
              'rotaApp': '/relatorio/business',
              'featureGate': 'RELATORIOS',
              'unlocked': true,
              'legacyIds': ['receita-recorrente', 'Receita recorrente'],
              'abas': [],
            },
            {
              'id': 'recorrencia',
              'titulo': 'Recorrência',
              'rotaApp': '/recorrencia',
              'featureGate': 'FINANCEIRO',
              'unlocked': true,
              'legacyIds': ['recorrencia'],
              'abas': [],
            },
            {
              'id': 'cobranca-auto',
              'titulo': 'Cobrança auto',
              'rotaApp': '/dunning',
              'featureGate': 'FINANCEIRO',
              'unlocked': true,
              'legacyIds': ['cobranca-auto'],
              'abas': [],
            },
          ],
        },
      ],
    },
    {
      'id': 'studio',
      'titulo': 'Studio',
      'papel': 'studio',
      'itens': [
        {
          'id': 'marca-propria',
          'titulo': 'Marca própria',
          'rotaApp': '/white-label',
          'featureGate': 'WHITE_LABEL',
          'unlocked': false,
          'upgradePlano': 'ENTERPRISE',
          'papel': 'studio',
          'legacyIds': ['marca-propria', 'Marca própria'],
          'abas': [],
        },
      ],
    },
  ],
};
